// ============================================================================
// ADVMEN SalesOS — Backend Global Constants, Roles & Permissions Matrix
// ============================================================================

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_REP: 'SALES_REP',
  TELECALLER: 'TELECALLER',
  MARKETING_SDR: 'MARKETING_SDR',
  FINANCE_VIEWER: 'FINANCE_VIEWER',
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const PERMISSION_KEYS = {
  // Leads & Pipeline
  LEAD_VIEW: 'lead.view',
  LEAD_CREATE: 'lead.create',
  LEAD_EDIT: 'lead.edit',
  LEAD_DELETE: 'lead.delete',
  LEAD_ASSIGN: 'lead.assign',
  LEAD_EXPORT: 'lead.export',
  
  // Deals & Pipelines
  DEAL_VIEW: 'deal.view',
  DEAL_CREATE: 'deal.create',
  DEAL_EDIT: 'deal.edit',
  DEAL_DELETE: 'deal.delete',
  
  // Contacts & Companies
  CONTACT_MANAGE: 'contact.manage',
  COMPANY_MANAGE: 'company.manage',

  // Telephony & Communications
  CALL_VIEW: 'call.view',
  CALL_MAKE: 'call.make',
  CALL_RECORDING_VIEW: 'call.recording.view',
  COMMUNICATION_SEND: 'communication.send',

  // Tasks, Meetings & Activities
  TASK_MANAGE: 'task.manage',
  MEETING_MANAGE: 'meeting.manage',
  ACTIVITY_VIEW: 'activity.view',

  // Proposals, Invoices & Payments
  PROPOSAL_MANAGE: 'proposal.manage',
  INVOICE_MANAGE: 'invoice.manage',
  PAYMENT_VIEW: 'payment.view',
  PAYMENT_MANAGE: 'payment.manage',

  // Intelligence & AI
  AI_USE: 'ai.use',
  AI_ADMIN: 'ai.admin',

  // Automations & Reports
  AUTOMATION_MANAGE: 'automation.manage',
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',

  // Administration & Tenant Settings
  USER_MANAGE: 'user.manage',
  ORGANIZATION_MANAGE: 'organization.manage',
  BILLING_MANAGE: 'billing.manage',
  INTEGRATION_MANAGE: 'integration.manage',
  AUDIT_VIEW: 'audit.view',
  SUPER_ADMIN_OPERATE: 'superadmin.operate',
} as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS];

// Default Role Permissions Mapping
export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  SUPER_ADMIN: Object.values(PERMISSION_KEYS),
  
  ORG_ADMIN: [
    PERMISSION_KEYS.LEAD_VIEW,
    PERMISSION_KEYS.LEAD_CREATE,
    PERMISSION_KEYS.LEAD_EDIT,
    PERMISSION_KEYS.LEAD_DELETE,
    PERMISSION_KEYS.LEAD_ASSIGN,
    PERMISSION_KEYS.LEAD_EXPORT,
    PERMISSION_KEYS.DEAL_VIEW,
    PERMISSION_KEYS.DEAL_CREATE,
    PERMISSION_KEYS.DEAL_EDIT,
    PERMISSION_KEYS.DEAL_DELETE,
    PERMISSION_KEYS.CONTACT_MANAGE,
    PERMISSION_KEYS.COMPANY_MANAGE,
    PERMISSION_KEYS.CALL_VIEW,
    PERMISSION_KEYS.CALL_MAKE,
    PERMISSION_KEYS.CALL_RECORDING_VIEW,
    PERMISSION_KEYS.COMMUNICATION_SEND,
    PERMISSION_KEYS.TASK_MANAGE,
    PERMISSION_KEYS.MEETING_MANAGE,
    PERMISSION_KEYS.ACTIVITY_VIEW,
    PERMISSION_KEYS.PROPOSAL_MANAGE,
    PERMISSION_KEYS.INVOICE_MANAGE,
    PERMISSION_KEYS.PAYMENT_VIEW,
    PERMISSION_KEYS.PAYMENT_MANAGE,
    PERMISSION_KEYS.AI_USE,
    PERMISSION_KEYS.AI_ADMIN,
    PERMISSION_KEYS.AUTOMATION_MANAGE,
    PERMISSION_KEYS.REPORT_VIEW,
    PERMISSION_KEYS.REPORT_EXPORT,
    PERMISSION_KEYS.USER_MANAGE,
    PERMISSION_KEYS.ORGANIZATION_MANAGE,
    PERMISSION_KEYS.BILLING_MANAGE,
    PERMISSION_KEYS.INTEGRATION_MANAGE,
    PERMISSION_KEYS.AUDIT_VIEW,
  ],

  SALES_MANAGER: [
    PERMISSION_KEYS.LEAD_VIEW,
    PERMISSION_KEYS.LEAD_CREATE,
    PERMISSION_KEYS.LEAD_EDIT,
    PERMISSION_KEYS.LEAD_EXPORT,
    PERMISSION_KEYS.DEAL_VIEW,
    PERMISSION_KEYS.DEAL_CREATE,
    PERMISSION_KEYS.DEAL_EDIT,
    PERMISSION_KEYS.CONTACT_MANAGE,
    PERMISSION_KEYS.COMPANY_MANAGE,
    PERMISSION_KEYS.CALL_VIEW,
    PERMISSION_KEYS.CALL_MAKE,
    PERMISSION_KEYS.CALL_RECORDING_VIEW,
    PERMISSION_KEYS.COMMUNICATION_SEND,
    PERMISSION_KEYS.TASK_MANAGE,
    PERMISSION_KEYS.MEETING_MANAGE,
    PERMISSION_KEYS.ACTIVITY_VIEW,
    PERMISSION_KEYS.PROPOSAL_MANAGE,
    PERMISSION_KEYS.INVOICE_MANAGE,
    PERMISSION_KEYS.PAYMENT_VIEW,
    PERMISSION_KEYS.AI_USE,
    PERMISSION_KEYS.REPORT_VIEW,
    PERMISSION_KEYS.REPORT_EXPORT,
    PERMISSION_KEYS.USER_MANAGE,
  ],

  SALES_REP: [
    PERMISSION_KEYS.LEAD_VIEW,
    PERMISSION_KEYS.LEAD_CREATE,
    PERMISSION_KEYS.LEAD_EDIT,
    PERMISSION_KEYS.DEAL_VIEW,
    PERMISSION_KEYS.DEAL_CREATE,
    PERMISSION_KEYS.DEAL_EDIT,
    PERMISSION_KEYS.CONTACT_MANAGE,
    PERMISSION_KEYS.COMPANY_MANAGE,
    PERMISSION_KEYS.CALL_VIEW,
    PERMISSION_KEYS.CALL_MAKE,
    PERMISSION_KEYS.COMMUNICATION_SEND,
    PERMISSION_KEYS.TASK_MANAGE,
    PERMISSION_KEYS.MEETING_MANAGE,
    PERMISSION_KEYS.ACTIVITY_VIEW,
    PERMISSION_KEYS.PROPOSAL_MANAGE,
    PERMISSION_KEYS.AI_USE,
    PERMISSION_KEYS.REPORT_VIEW,
  ],

  TELECALLER: [
    PERMISSION_KEYS.LEAD_VIEW,
    PERMISSION_KEYS.LEAD_EDIT,
    PERMISSION_KEYS.CALL_VIEW,
    PERMISSION_KEYS.CALL_MAKE,
    PERMISSION_KEYS.COMMUNICATION_SEND,
    PERMISSION_KEYS.TASK_MANAGE,
    PERMISSION_KEYS.ACTIVITY_VIEW,
    PERMISSION_KEYS.AI_USE,
  ],

  MARKETING_SDR: [
    PERMISSION_KEYS.LEAD_VIEW,
    PERMISSION_KEYS.LEAD_CREATE,
    PERMISSION_KEYS.LEAD_EDIT,
    PERMISSION_KEYS.CONTACT_MANAGE,
    PERMISSION_KEYS.COMMUNICATION_SEND,
    PERMISSION_KEYS.ACTIVITY_VIEW,
    PERMISSION_KEYS.AI_USE,
    PERMISSION_KEYS.REPORT_VIEW,
  ],

  FINANCE_VIEWER: [
    PERMISSION_KEYS.INVOICE_MANAGE,
    PERMISSION_KEYS.PAYMENT_VIEW,
    PERMISSION_KEYS.PROPOSAL_MANAGE,
    PERMISSION_KEYS.REPORT_VIEW,
    PERMISSION_KEYS.REPORT_EXPORT,
  ],
};

export const AI_ACTION_LEVELS = {
  READ_ONLY: 'READ_ONLY',     // Timeline/lead summaries (Auto display)
  ASSISTIVE: 'ASSISTIVE',     // Draft email/WhatsApp (User approval required)
  OPERATIONAL: 'OPERATIONAL', // Create task (Configurable auto/manual approval)
  EXTERNAL: 'EXTERNAL',       // Send outbound call/message (Explicit approval required)
  FINANCIAL: 'FINANCIAL',     // Change invoice/payment (Privileged human approval only)
} as const;

export const QUEUE_NAMES = {
  NOTIFICATIONS: 'notifications',
  COMMUNICATIONS: 'communications',
  REPORTS: 'reports',
  IMPORTS: 'imports',
  AI: 'ai',
  AUTOMATION: 'automation',
  BILLING: 'billing',
  MEDIA: 'media',
} as const;
